Feature/scroll
Space2Study-Project/Space2Study-FrontEnd pull request #102
Opened 2023-11-27 16:44 UTC by LeonidShamarin

https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/122298176/6f9a4a15-70ad-4416-a8d4-bb6e9d1727a5

Fixed, now when you press the button (Space2study), page  scroll to the top

2023-11-27 19:32 UTC, AndriiNasadiuk requested changes
needs test coverage >= 80%

2023-11-27 19:35 UTC, AndriiNasadiuk commented on .vscode/settings.json
needs to explain

2023-11-27 19:36 UTC, AndriiNasadiuk commented on package-lock.json
13518-13521 rows needs to explain

2023-11-27 19:38 UTC, AndriiNasadiuk reviewed
it seems too complicated. Needs explanations on meeting

2023-11-28 09:59 UTC, closed without merging

2023-11-28 09:59 UTC, LeonidShamarin commented
Another pull request make