change when press “Space2Study” logo buttom page scrooll to the top
Space2Study-Project/Space2Study-FrontEnd pull request #113
Opened 2023-11-28 15:42 UTC by LeonidShamarin

Close #65 
The system scrolls back to the home page welcoming block after clicking on the “Space2Study” logo button on the header.
Return to the previous commit, make new branch from my previous

https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/122298176/a17d47c8-ec0d-4786-b69a-47b18d1bfa96

2023-11-28 15:58 UTC, vlad-khrychov commented
Please, don`t create new PR-s when added commits. For one task we create one PR.

2023-11-28 16:07 UTC, vlad-khrychov requested changes

2023-11-28 16:07 UTC, vlad-khrychov commented on src/components/scroll-to-top-button/ScrollToTopButton.jsx
> +  ScrollToTopButton.goToTop = goToTop
It is not convenient way to export of function

2023-11-28 16:07 UTC, vlad-khrychov commented on src/containers/layout/navbar/NavBar.jsx
> +    ScrollToTopButton.goToTop(mainWithFooter)
For now `goToTop` don`t obtain any arguments, but it will be correct way to call it when we change function.

2023-11-28 16:07 UTC, vlad-khrychov commented on src/containers/layout/navbar/NavBar.jsx
> +      <ScrollToTopButton element={mainWithFooter} />
We must not use this component here

2023-11-28 19:32 UTC, LeonidShamarin commented on src/components/scroll-to-top-button/ScrollToTopButton.jsx
> +  ScrollToTopButton.goToTop = goToTop
It was deleted, i resolve it in another way

2023-11-28 19:32 UTC, LeonidShamarin commented on src/containers/layout/navbar/NavBar.jsx
> +    ScrollToTopButton.goToTop(mainWithFooter)
It was deleted, i resolve it in another way

2023-11-28 19:32 UTC, LeonidShamarin commented on src/containers/layout/navbar/NavBar.jsx
> +      <ScrollToTopButton element={mainWithFooter} />
It was deleted, i resolve it in another way

2023-11-29 08:25 UTC, AndriiNasadiuk commented on src/containers/layout/navbar/NavBar.jsx
Did it really need to be changed homePath to welcome route? UI behavior the same with welcome and home. (rows 33- 53)

2023-11-29 08:27 UTC, AndriiNasadiuk requested changes
Did it really need to be changed homePath to welcome route? UI behavior the same with welcome and home routes. And it isn’t  required in task. (rows 33- 53)

2023-11-29 09:02 UTC, LeonidShamarin commented
> Did it really need to be changed homePath to welcome route? UI behavior the same with welcome and home routes. And it isn’t required in task. (rows 33- 53)

It says there, - "the system scrolls back to the home page welcoming block", and I write specific  route to welcome block

2023-11-29 09:10 UTC, AndriiNasadiuk commented
> > Did it really need to be changed homePath to welcome route? UI behavior the same with welcome and home routes. And it isn’t required in task. (rows 33- 53)
> 
> It says there, - "the system scrolls back to the home page welcoming block", and I write specific route to welcome block



> welcoming

Can’t see where is written you have to change route to welcome.

2023-11-29 09:34 UTC, AndriiNasadiuk commented on src/containers/layout/navbar/NavBar.jsx
do we really need to change home path to welcome path? rows 32 - 35

2023-11-29 14:43 UTC, AndriiNasadiuk approved these changes
ok

2023-11-29 16:55 UTC, ArtemHolikov approved these changes
Nice. Now looks better

2023-11-29 17:20 UTC, Mygal-Alex approved these changes
Now looks good

2023-11-29 17:24 UTC, marianamartsy approved these changes
ok

2023-11-30 11:23 UTC, vlad-khrychov approved these changes

2023-11-30 12:04 UTC, merged