added tests
Space2Study-Project/Space2Study-FrontEnd pull request #114
Opened 2023-11-29 14:01 UTC by Mygal-Alex

<img width="438" alt="image" src="https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/101183408/2d9306e1-cc9c-438d-9b03-d500be77d5a8">

<img width="527" alt="image" src="https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/101183408/b367df0f-3c7b-424d-8dd0-06ca112877ba">

2023-11-29 16:57 UTC, AndriiNasadiuk approved these changes
ok

2023-11-29 16:59 UTC, ArtemHolikov approved these changes
Nice tests

2023-11-29 17:29 UTC, marianamartsy approved these changes
god job
ps. make, please, the pull request title more understandable than it currently is 👍

2023-11-30 10:02 UTC, LeonidShamarin approved these changes
Ok

2023-11-30 11:28 UTC, vlad-khrychov requested changes

2023-11-30 11:28 UTC, vlad-khrychov commented on tests/unit/components/input-with-icon/InputWithIcon.spec.jsx
> +    startIcon: <CloudUploadIcon /> // random test icon
```suggestion
    startIcon: <CloudUploadIcon />
```
What about the comment rule in this project? I think they are forbidden.

2023-11-30 11:36 UTC, Mygal-Alex commented on tests/unit/components/input-with-icon/InputWithIcon.spec.jsx
> +    startIcon: <CloudUploadIcon /> // random test icon
Yes, I'm sorry
I left a comment to explain the solution. 
and I'm deleting it now.

2023-11-30 11:45 UTC, merged