add test for AppContentSwitcher component
Space2Study-Project/Space2Study-FrontEnd pull request #130
Opened 2023-11-30 11:11 UTC by LeonidShamarin

add test for AppContentSwitcher component

2023-11-30 14:50 UTC, AndriiNasadiuk requested changes
it should be 1 expect function for 1 it block, isn’t it ?

2023-11-30 14:59 UTC, LeonidShamarin commented
> it should be 1 expect function for 1 it block, isn’t it ?

Please explain what you mean

2023-11-30 21:19 UTC, AndriiNasadiuk approved these changes

2023-11-30 21:33 UTC, marianamartsy approved these changes
ok

2023-11-30 22:00 UTC, ArtemHolikov approved these changes
Seems good, but why u didn`t placed **switchOptions** function inside test case?

2023-12-01 09:15 UTC, vlad-khrychov requested changes

2023-12-01 09:15 UTC, vlad-khrychov commented on tests/unit/components/app-content-switcher/AppContentSwitcher.spec.jsx
> +  }
We can use different props for different test cases for testing all conditions renders. 
Try to provide `switchOptions`  with only left property, only right property, without both and like now

2023-12-01 12:28 UTC, vlad-khrychov requested changes
After deleting 2 files you can merge this PR without my approval

2023-12-01 12:28 UTC, vlad-khrychov commented on tests/unit/components/app-content-switcher/AppContentSwitcher.spec.jsx
This file is ok

2023-12-01 12:28 UTC, vlad-khrychov commented on tests/unit/containers/tutor-home-page/add-photo-step/AddPhotoStep.spec.jsx
Delete this file from PR

2023-12-01 12:28 UTC, vlad-khrychov commented on tests/unit/containers/tutor-home-page/language-step/LanguageStep.spec.jsx
Delete file from PR

2023-12-01 12:59 UTC, vlad-khrychov approved these changes

2023-12-01 14:08 UTC, Mygal-Alex approved these changes

2023-12-01 14:08 UTC, merged