Test #99 popup dialog
Space2Study-Project/Space2Study-FrontEnd pull request #134
Opened 2023-11-30 14:57 UTC by AndriiNasadiuk

close #99

2023-11-30 20:24 UTC, marianamartsy reviewed
will you change this code like we talked on meeting?

2023-11-30 21:34 UTC, AndriiNasadiuk commented
> will you change this code like we talked on meeting?

Maybe later, not now)

2023-11-30 21:58 UTC, ArtemHolikov approved these changes
Seems correctly. but don`t forget to delete Loader from this commit before merge.

2023-12-01 09:08 UTC, vlad-khrychov commented
In task says about "closing" of modal window, but I don`t see test about it (`not.toBeInTheDocument()`)

2023-12-08 14:09 UTC, Mygal-Alex approved these changes
bug#131Sign-in/Sign-up

2023-12-08 14:09 UTC, marianamartsy approved these changes
👍

2023-12-08 14:18 UTC, LeonidShamarin approved these changes

2023-12-08 19:47 UTC, vlad-khrychov requested changes

2023-12-08 19:47 UTC, vlad-khrychov commented on tests/unit/components/loader/Loader.spec.jsx
Delete this empty file from pull request

2023-12-09 09:16 UTC, AndriiNasadiuk commented on tests/unit/components/loader/Loader.spec.jsx
Done

2023-12-12 11:20 UTC, merged