add test to Subjects component #121
Space2Study-Project/Space2Study-FrontEnd pull request #135
Opened 2023-11-30 15:04 UTC by Mygal-Alex

![image](https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/101183408/207fcacf-fa31-43bf-9ef0-bea0efc54f60)

2023-11-30 15:45 UTC, AndriiNasadiuk approved these changes
you can ommit beforeEach(), if you have 1 it() statement

2023-11-30 15:55 UTC, marianamartsy approved these changes
ok
ps. beforeEach don't needed in this case, I guess

2023-11-30 20:41 UTC, LeonidShamarin approved these changes

2023-11-30 21:57 UTC, ArtemHolikov approved these changes
What can be easier?) Good job. But can we render Subjects inside functional block? Why it`s better?

2023-12-01 11:27 UTC, vlad-khrychov requested changes

2023-12-01 11:27 UTC, vlad-khrychov commented on tests/unit/pages/subjects/Subjects.spec.jsx
Mock `PageWrapper` and check 2 conditions (two  `expect` or two `it`) according to the task.

2023-12-04 14:29 UTC, vlad-khrychov approved these changes

2023-12-04 16:14 UTC, merged