solved test #117
Space2Study-Project/Space2Study-FrontEnd pull request #136
Opened 2023-11-30 15:29 UTC by AndriiNasadiuk

close #117 
<img width="725" alt="Знімок екрана 2023-11-30 о 17 26 31" src="https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/123100628/94213f21-97be-4319-b9ad-37dafa9f5fcd">

2023-11-30 15:58 UTC, marianamartsy approved these changes
👍

2023-11-30 20:40 UTC, LeonidShamarin approved these changes

2023-11-30 21:55 UTC, ArtemHolikov approved these changes
Nice, yes. Correct

2023-12-01 09:05 UTC, vlad-khrychov requested changes

2023-12-01 09:05 UTC, vlad-khrychov commented on tests/unit/pages/find-offers/FindOffers.spec.jsx
In task was described 2 scenarios, we need at least 2 `expect` (or 2 `it`)
![image](https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/67462207/689db5d1-f683-4a8c-b1a9-08a7679b785d)

2023-12-01 09:12 UTC, AndriiNasadiuk commented on tests/unit/pages/find-offers/FindOffers.spec.jsx
ok, I’ll do the second

2023-12-01 10:13 UTC, AndriiNasadiuk commented on tests/unit/pages/find-offers/FindOffers.spec.jsx
I have done it

2023-12-01 10:19 UTC, Mygal-Alex approved these changes

2023-12-04 19:33 UTC, vlad-khrychov approved these changes

2023-12-04 19:37 UTC, merged