Unit test for "Categories" page
Space2Study-Project/Space2Study-FrontEnd pull request #137
Opened 2023-11-30 15:57 UTC by marianamartsy

close #120 

- [x]  It should render page Categories  with text  in the document
![Zrzut ekranu 2023-11-30 o 16 21 58](https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/123500008/abe7f350-bca6-4cd4-87ea-e884706b3fc6)

![Zrzut ekranu 2023-11-30 o 16 41 26](https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/123500008/629bae0e-1869-432b-958d-f9cf36e599ff)

2023-11-30 19:50 UTC, AndriiNasadiuk approved these changes

2023-11-30 20:40 UTC, LeonidShamarin approved these changes

2023-11-30 21:44 UTC, ArtemHolikov approved these changes
The easiest test :) Can`t be bad)

2023-12-01 10:18 UTC, Mygal-Alex approved these changes

2023-12-01 10:54 UTC, vlad-khrychov requested changes

2023-12-01 10:54 UTC, vlad-khrychov commented on tests/unit/pages/categories/Categories.spec.jsx
We should mock `PageWrapper` and after that test Categories  (because word "Categories" can be changed in future and our tests must be independent).
Also according to the task we need at least 2 `it` (or 2 `expect`).
![image](https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/67462207/e428510e-7eb1-4c89-b71a-3eddd7aabac5)

2023-12-01 16:09 UTC, vlad-khrychov approved these changes

2023-12-01 16:32 UTC, merged