add test to AppTextField #122
Space2Study-Project/Space2Study-FrontEnd pull request #138
Opened 2023-11-30 16:12 UTC by Mygal-Alex

<img width="456" alt="image" src="https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/101183408/792f470e-eb50-4b89-b8b9-7f4828b9f46a">

<img width="523" alt="image" src="https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/101183408/bc53d67e-b4f1-47be-875e-1b81a490e627">

2023-11-30 19:49 UTC, AndriiNasadiuk approved these changes

2023-11-30 20:27 UTC, marianamartsy approved these changes
👍

2023-11-30 20:39 UTC, LeonidShamarin approved these changes

2023-11-30 21:55 UTC, ArtemHolikov approved these changes
Correct

2023-12-01 11:16 UTC, vlad-khrychov commented
Pleas add `close #122` to description

2023-12-01 11:25 UTC, vlad-khrychov requested changes

2023-12-01 11:25 UTC, vlad-khrychov commented on tests/unit/components/app-text-field/AppTextField.spec.jsx
> +    const errorText = screen.queryByText(/TEST_ERROR/)
Here we need to use `data-testId` or delete this and 25 row

2023-12-01 14:12 UTC, merged