add test to TitleWithDescription #126
Space2Study-Project/Space2Study-FrontEnd pull request #139
Opened 2023-11-30 19:32 UTC by Mygal-Alex

<img width="554" alt="image" src="https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/101183408/36af947b-51db-45b4-a781-c812ddaf4379">
<img width="525" alt="image" src="https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/101183408/5cea7b38-b74d-4bb9-a250-be8933a492c5">

2023-11-30 19:48 UTC, AndriiNasadiuk approved these changes

2023-11-30 20:29 UTC, marianamartsy approved these changes
👍

2023-11-30 20:38 UTC, LeonidShamarin approved these changes

2023-11-30 21:53 UTC, ArtemHolikov approved these changes
Good

2023-12-01 11:11 UTC, vlad-khrychov commented
Add `close #126` to description

2023-12-01 11:15 UTC, vlad-khrychov requested changes

2023-12-01 11:15 UTC, vlad-khrychov commented on tests/unit/components/title-with-description/TitleWithDescription.spec.jsx
> +  })
I think this test we can delete. It is like `expect(2).not.toEqual(3)`.
```suggestion
```

2023-12-01 14:02 UTC, merged