Task #118 done
Space2Study-Project/Space2Study-FrontEnd pull request #140
Opened 2023-11-30 20:03 UTC by AndriiNasadiuk

close #118 

<img width="847" alt="Знімок екрана 2023-11-30 о 22 02 31" src="https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/123100628/f564cb3b-218a-41b0-88ab-efe8f9940d19">

<img width="781" alt="Знімок екрана 2023-11-30 о 22 02 20" src="https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/123100628/66e2f0b8-53ca-4dcc-b2a1-4d969a855d7e">

2023-11-30 20:30 UTC, LeonidShamarin approved these changes

2023-11-30 20:36 UTC, marianamartsy approved these changes
Please add a topic if this task is related to PopupDialog or GeneralInfoStep ;-)

GeneralInfoStep approved

2023-11-30 21:52 UTC, ArtemHolikov approved these changes
Seems good, but do we have another way to write test with delay in PopupDialog component?

2023-12-01 10:18 UTC, Mygal-Alex approved these changes

2023-12-01 15:29 UTC, vlad-khrychov requested changes
Not correct way to run tests whith mocks

2023-12-01 15:29 UTC, vlad-khrychov commented on tests/unit/containers/tutor-home-page/general-info-step/GeneralInfoStep.spec.jsx
We need to delete this file from this PR?

2023-12-01 15:29 UTC, vlad-khrychov commented on tests/unit/components/popup-dialog/PopupDialog.spec.jsx
> +    })
it is doesn`t work

2023-12-01 15:29 UTC, vlad-khrychov commented on tests/unit/components/popup-dialog/PopupDialog.spec.jsx
> +    })
Where you found this approach to run test? `vi.fn()` - https://vitest.dev/api/vi.html#vi-fn

2023-12-05 19:53 UTC, vlad-khrychov approved these changes
Well done

2023-12-05 20:08 UTC, merged