Unit test for "ImgTitleDescription" component
Space2Study-Project/Space2Study-FrontEnd pull request #146
Opened 2023-12-01 10:09 UTC by ArtemHolikov

close #124 

- [x] Test should check image, title and description render
![image](https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/102384883/85b6957a-9d20-404c-83ff-41ec0b34a4a2)
![image](https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/102384883/ab8a92d6-c108-451c-b829-ddc2ac4e85a6)

2023-12-01 11:16 UTC, LeonidShamarin approved these changes

2023-12-01 13:32 UTC, marianamartsy approved these changes
👍

2023-12-01 14:49 UTC, AndriiNasadiuk approved these changes

2023-12-01 16:47 UTC, Mygal-Alex approved these changes
👍👍👍👍

2023-12-01 23:05 UTC, vlad-khrychov requested changes
Everything is good, but we must mock all internal components

2023-12-01 23:05 UTC, vlad-khrychov commented on tests/unit/components/img-title-description/ImgTitleDescription.spec.jsx
Try to mock `TitleWithDescription`. We already have test on this component. 
Mock can be like `({title, description})=><div><span>title</span><span>description</span></div>`

2023-12-05 10:04 UTC, ArtemHolikov commented on tests/unit/components/img-title-description/ImgTitleDescription.spec.jsx
Mocked. Is everything good now?
![image](https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/102384883/07c45496-d079-41bf-a766-2482e6fd536b)

2023-12-05 20:09 UTC, merged