add test for videobox component
Space2Study-Project/Space2Study-FrontEnd pull request #147
Opened 2023-12-01 10:56 UTC by LeonidShamarin

Unit test for "VideoBox" component
![Снимок экрана (2811)1](https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/122298176/a25b5e4d-d07d-428a-8709-62eee208c734)
![Снимок экрана (2812)1](https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/122298176/78dadcdc-4f1b-45eb-bbe0-f7e0c7549b9b)

2023-12-04 19:42 UTC, vlad-khrychov commented on tests/unit/components/video-box/VideoBox.spec.jsx
> +import React from 'react'
Can we delete this import?
```suggestion
```

2023-12-06 11:18 UTC, marianamartsy approved these changes
👍

2023-12-06 18:27 UTC, Mygal-Alex approved these changes
test looks good

2023-12-07 18:53 UTC, AndriiNasadiuk requested changes
Rows 10 and 12 don’t have influence on coverage, so i would delete it

2023-12-07 18:53 UTC, AndriiNasadiuk commented
<img width="1792" alt="Знімок екрана 2023-12-07 о 20 51 07" src="https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/123100628/e58e2e57-cc10-493c-8891-3f6774377362">

2023-12-07 19:14 UTC, LeonidShamarin commented
> Rows 10 and 12 don’t have influence on coverage, so i would delete it

ok

2023-12-08 08:28 UTC, AndriiNasadiuk commented
> > Rows 10 and 12 don’t have influence on coverage, so i would delete it
> 
> ok

so "ok", but that rows still in the file))

2023-12-08 08:30 UTC, AndriiNasadiuk approved these changes
nice

2023-12-08 08:31 UTC, ArtemHolikov approved these changes
👍

2023-12-08 09:47 UTC, vlad-khrychov approved these changes

2023-12-08 10:00 UTC, merged