add test for AccordionWithImage component
Space2Study-Project/Space2Study-FrontEnd pull request #162
Opened 2023-12-05 11:23 UTC by LeonidShamarin

Add test for the AccordionWithImage component

2023-12-06 11:22 UTC, marianamartsy reviewed
you need to mock Accordions component, I guess

2023-12-07 07:36 UTC, LeonidShamarin commented
> you need to mock Accordions component, I guess

We need to mock that component witch inside your components.

2023-12-07 10:52 UTC, LeonidShamarin commented
> you need to mock Accordions component, I guess

Ok, I added mock for the Accordions component.

2023-12-07 11:26 UTC, marianamartsy approved these changes
👍

2023-12-08 08:31 UTC, Mygal-Alex approved these changes
👍

2023-12-08 08:32 UTC, ArtemHolikov approved these changes
👍

2023-12-08 08:34 UTC, AndriiNasadiuk requested changes
it looks like you forget some expectations after row 41 ?

2023-12-08 09:55 UTC, vlad-khrychov reviewed
Try to add one more "it" that i described. If it does not work you can merge like now.

2023-12-08 09:55 UTC, vlad-khrychov commented on tests/unit/components/accordion-with-image/AccordionWithImage.spec.jsx
> +    expect(mockedAccordions).toBeInTheDocument()
Maybe we can try ti find content of accordion? Maybe `getByText("Item 1")` for click and expect to obtain `getByText("Description 1")`  in the document.

2023-12-08 10:42 UTC, AndriiNasadiuk commented on tests/unit/components/accordion-with-image/AccordionWithImage.spec.jsx
> +    expect(mockedAccordions).toBeInTheDocument()
and what about coverage?
<img width="1083" alt="image" src="https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/123100628/78b539ca-f21f-4a3b-a85b-bd2b501a4b48">

2023-12-08 11:22 UTC, LeonidShamarin commented on tests/unit/components/accordion-with-image/AccordionWithImage.spec.jsx
> +    expect(mockedAccordions).toBeInTheDocument()
Mocking components using tools like vi.mock can sometimes lead to a decrease in code coverage. This is because the actual implementation of the component is replaced with a mock, and the test may not cover the mocked behavior in the same way it would cover the real behavior.

2023-12-08 13:17 UTC, AndriiNasadiuk commented on tests/unit/components/accordion-with-image/AccordionWithImage.spec.jsx
> +    expect(mockedAccordions).toBeInTheDocument()
ok, but everybody will have to approve me test #99, where i have 75% funcs coverage))

2023-12-08 13:18 UTC, AndriiNasadiuk approved these changes

2023-12-08 20:35 UTC, vlad-khrychov requested changes
You're on the right way, just a little more to do.

2023-12-08 20:35 UTC, vlad-khrychov commented on tests/unit/components/accordion-with-image/AccordionWithImage.spec.jsx
> +  it('should open content when user clicks on the title', () => {
This test is false positive. You can delete fireEvent.click(titleElement) and test will be passed.
So, you need add onClick in your mock, and call inside this handler `props.onChange(props.activeIndex)`. 
Also you need render **all** `title`s in mocked component (with `map`) and render only one description (according to the `props.activeIndex`)

2023-12-09 19:50 UTC, LeonidShamarin commented on tests/unit/components/accordion-with-image/AccordionWithImage.spec.jsx
> +    expect(mockedAccordions).toBeInTheDocument()
Fixed, now 100%
![Снимок экрана (2867)](https://github.com/Space2Study-Project/Space2Study-FrontEnd/assets/122298176/ab2063c4-6e70-4b58-a0c7-3705177891d5)
 now 100%

2023-12-10 08:58 UTC, vlad-khrychov approved these changes

2023-12-11 19:26 UTC, merged