Implementation general step component
Space2Study-Project/Space2Study-FrontEnd pull request #168
Opened 2023-12-08 09:19 UTC by ArtemHolikov

close #154 

- [x] Implement the general info step to used it in both student and tutor
- [x] First name and Last name of a user should be pulled from first registration form.
- [x] Country and city have to be pulled from server on input focus
- [x] Additional info length can't be more than 70 symbols

2023-12-08 13:07 UTC, marianamartsy approved these changes
👍

2023-12-08 13:08 UTC, AndriiNasadiuk approved these changes
👌

2023-12-08 13:09 UTC, Mygal-Alex approved these changes
👍

2023-12-08 14:11 UTC, LeonidShamarin approved these changes

2023-12-10 09:43 UTC, vlad-khrychov requested changes

2023-12-10 09:43 UTC, vlad-khrychov commented on src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
> +    }
Let`s think on planning what we should do when something went wrong. Generally user do not see on console. Maybe we can create popup for all errors in stepper? It will be another task but think about it.

2023-12-10 09:43 UTC, vlad-khrychov commented on src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
> +      }
What happen when `selectedCountry` is null? I think that we should call `setCity([])` in this case.

2023-12-10 09:43 UTC, vlad-khrychov commented on src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
> +  const { t } = useTranslation()
A lot of hooks and we can divide them by their roles. Part of them about **city** and **country**, another part about **name** and **lastName** and also `useTranslation` hook. Maybe we can group hooks (use custom hook for grouping).

2023-12-10 09:43 UTC, vlad-khrychov commented on tests/unit/containers/tutor-home-page/general-info-step/GeneralInfoStep.spec.jsx
I haven`t check it yet. We have discussion in component. In future i will check how tests are working. On first view it seems good.

2023-12-11 20:56 UTC, ArtemHolikov commented on src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
> +  const { t } = useTranslation()
I created 2 custom hooks for cities/countries and name. But I can't understand, why we need create custom hook for useTranslation hook. It will be extra move, don't think so? Or I didn't understand what you want

2023-12-13 17:24 UTC, vlad-khrychov approved these changes

2023-12-13 17:24 UTC, merged